export const homeData = [
    {
      id: 1,
      name: "Sand Dust",
      rating: 4.7,
      time: "2hr : 22mins",
      desc: "Sand and dust storms (SDS), also known as sirocco, haboob, yellow dust, white storms, and the harmattan, are a natural phenomenon linked with land and water management and climate change.",
      starring: "Karen Gilchrist, James Earl Jones",
      genres: "Action",
      tags: "Action, Adventures, Horror",
      cover: "../images/home1.jpg",
      video: "../video/video1.mp4",
      date: "20-Jan-1997",
    },
    {
      id: 2,
      name: "skull island",
      rating: 4.6,
      time: "2hr : 22mins",
      desc: "The island, like its inhabitants, is wholly fictional. Kong's island home in the Pacific makes its first appearance, along with Kong himself, in the 1933 film King Kong. ",
      starring: "Brenda Chapman, Jeff Nathanson",
      genres: "Adventures",
      tags: "Adventures,Animation,Family",
      cover: "../images/home2.jpg",
      video: "../video/video2.mp4",
      date: "10-JUL-2021",
    },
    {
      id: 3,
      name: "Pirates Sea",
      rating: 4.8,
      time: "2hr : 22mins",
      desc: "Piracy is an act of robbery or criminal violence by ship or boat-borne attackers upon another ship or a coastal area, typically with the goal of stealing cargo and other valuable items or properties. ",
      starring: "James Chinlund, Jeff Nathanson",
      genres: "Adventures",
      tags: "Adventures,Action ",
      cover: "../images/home3.jpg",
      video: "../video/video3.mp4",
      date: "20-FEB-2010",
    },
    {
      id: 4,
      name: "Sand Dust",
      rating: 4.9,
      time: "2hr : 22mins",
      desc: "Sand and dust storms (SDS), also known as sirocco, haboob, yellow dust, white storms, and the harmattan, are a natural phenomenon linked with land and water management and climate change.",
      starring: "Karen Gilchrist, James Earl Jones",
      genres: "Action",
      tags: "Action, Adventures, Horror",
      cover: "../images/home4.jpg",
      video: "../video/video4.mp4",
      date: "12-Aug-2015",
    },
  ]